### ISSUE TITLE
Remote version file missing (plus several more)

### ISSUE THREAD

**Issue by HebaruSan** [linuxgurugamer/SpaceTuxLibrary#2]
Follow-up to linuxgurugamer/BetterTimeWarpContinued#25 and linuxgurugamer/GravityTurn#4.

Here's the list of spacetux URLs that are failing currently:

- [x] https://ksp.spacetux.net/avc/Workshop
- [x] https://ksp.spacetux.net/avc/SpaceTuxLibrary
- [x] https://ksp.spacetux.net/avc/PartInfo
- [x] http://ksp/spacetux.net/avc/TrimIndicators
- [x] http://ksp/spacetux.net/avc/NASA_CountDown
- [x] http://ksp.spacetux.net/avc/kerbcam
- [x] http://ksp.spacetux.net/avc/SpacedockReBoxed
- [x] http://ksp.spacetux.net/avc/Mk-X
- [x] http://ksp.spacetux.net/avc/KerbalConstructionTime-180
- [x] http://ksp.spacetux.net/avc/KerbalConstructionTime-173
- [x] http://ksp.spacetux.net/avc/Planetary-Diversity
- [x] http://ksp.spacetux.net/OrbitalColony

**Comment by HebaruSan** [comment]
I guess TrimIndicators and NASA-CountDown will need version file updates since those URLs are malformed (host is just /ksp/ and spacetux.net is after the slash).

**Comment by HebaruSan** [comment]
- PicoPort has a version file in the repo but not in the download
- But I can't create an issue for it over there because the PicoPort repository has issues disabled

Replaced by linuxgurugamer/PicoPort#3.

**Comment by linuxgurugamer** [comment]
thanks, I enabled the issues and added it, will try to get it later this evening.
I'll look at the others, had to change my process, obviously some files are being missed

**Comment by linuxgurugamer** [comment]
I just finished updating all the errors, could you run through them again, please.  I assume that's from the output of the bot.
I had to update most of them, renamed 2 files to match what was in the file

Thx

**Comment by HebaruSan** [comment]
Thanks for taking a look. The new error for this mod is:

![image](https://user-images.githubusercontent.com/1559108/82580763-3a3fb300-9b55-11ea-8c9a-d3878352965a.png)

I assume that's because the wrong version file is in it now.

![image](https://user-images.githubusercontent.com/1559108/82580883-678c6100-9b55-11ea-968f-f6cf01175bce.png)

**Comment by HebaruSan** [comment]
I checked the others and updated the fixed ones (most of them) with checkmarks in the OP. Thanks!

Yes, the bot now includes this output.  http://status.ksp-ckan.space/

![image](https://user-images.githubusercontent.com/1559108/82582032-0cf40480-9b57-11ea-98a6-fb531d6a879a.png)

**Comment by linuxgurugamer** [comment]
Ok.  I missed a couple and one had the wrong file i the config
All updated on Github, these three are waiting for spacedock, the upload to spacedock is hanging right now:

SpaceTuxLibrary
OrbitalColony
PlanetaryDiversity
SpaceDockReBoxed

I'll ping you when I get the uploads to spacedock finished

**Comment by linuxgurugamer** [comment]
Ping.  All files uploaded
Thank you

**Comment by HebaruSan** [comment]
The files look good to me now, but the bot's warnings for two of them haven't cleared yet. I expect that they will eventually, and I'll close this when that happens.

**Comment by HebaruSan** [comment]
All good now. Thanks for your patience!

**Comment by linuxgurugamer** [comment]
Thank YOU!

**Comment by HebaruSan** [comment]
Hey @linuxgurugamer, now WaypointManager is suffering from this. I'd create an issue on its repo but issues aren't enabled.

- https://ksp.spacetux.net/avc/WaypointManager

**Comment by linuxgurugamer** [comment]
Nuts.  It should be http, I'll get it updated

**Comment by linuxgurugamer** [comment]
Updated, thanks.  I also enabled the issues for WayPointManager

Let me know if it happens again, sometimes my fingers just type without any intelligence behind them

**Comment by HebaruSan** [comment]
Looks good now, the warning is cleared. :tada:
