### ISSUE TITLE
Version file missing from latest release

### ISSUE THREAD

**Issue by HebaruSan** [linuxgurugamer/SpaceTuxLibrary#3]
Previous releases of this mod shipped a GameData/SpaceTuxLibrary/SpaceTuxLibrary.version file.

![image](https://user-images.githubusercontent.com/1559108/85184207-8a915a00-b254-11ea-9f0a-3db97eadb181.png)

Now it's gone, replaced with a ButtonManager.version file that doesn't have the right data in it.

![image](https://user-images.githubusercontent.com/1559108/85184237-a09f1a80-b254-11ea-93cd-ddc19c1fad42.png)

This has blocked this release from indexing in CKAN.

@linuxgurugamer

**Comment by linuxgurugamer** [comment]
Oh, nuts.
This should have 6 different .version files in it. Thanks, I'll figure out what's wrong

**Comment by linuxgurugamer** [comment]
Problem was in my build script, fixed and updating now

**Comment by HebaruSan** [comment]
This is not fixed.
https://spacedock.info/mod/2210/SpaceTux%20Library/download/0.0.3

**Comment by linuxgurugamer** [comment]
oh, spacedock, yes, thank you, fixing now

**Comment by linuxgurugamer** [comment]
Crap, seems that Spacedock doesn't want to delete the file when I tell it to, I'm going to have to do a version bump for this

**Comment by linuxgurugamer** [comment]
I've just uploaded 0.0.3.1 to spacedock and github, hopefully this solves the problem

**Comment by HebaruSan** [comment]
Yup, that worked. :tada: 

https://github.com/KSP-CKAN/CKAN-meta/commit/5f1d3f52766ae52c95f8683fa696eb0d05602955
