### ISSUE TITLE
AVC reports wrong ButtonManager version

### ISSUE THREAD

**Issue by davedev** [linuxgurugamer/SpaceTuxLibrary#4]
When starting the game I get a notice from AVC that ButtonManager has an update available.  It reports current version as 0.0.1 and a new version available 0.0.3.1.  

I can see just by checking this repo that your latest version is still 0.0.1.0, unless the ButtonManager.version file with last commit ba5447a is outdated.

It might be getting the "new version" data from here:  http://ksp.spacetux.net/avc/SpaceTuxLibrary ?

Screenshot attached.  This is the first time I've needed to post an issue to you so, I'll take the opportunity to thank you for all your work over the years.  Thanks.

![Annotation 2020-06-25 194108](https://user-images.githubusercontent.com/4571729/85805994-db54f700-b71b-11ea-8bb4-e72208cf0db0.png)

**Comment by linuxgurugamer** [comment]
You can ignore this for now.  No mod uses that, it's there for an upcoming update.  The latest has not yet been commited to github, which is why you see it.
Thanks for pointing it out to me
