### ISSUE TITLE
Reverts calendar to y1d1

### ISSUE THREAD

**Issue by armegeddon** [linuxgurugamer/SpaceTuxLibrary#5]
Loading an existing game using the 0.0.5.1 release causes the calendar to revert to year 1, day 1 and appears to reset the universe to an initial state. This destroys any craft in space, or landed on any planet.

**Comment by linuxgurugamer** [comment]
That's impossible.  The only change was to KSP_Log.  You must have updated other stuff at the same time.  Without a log file, this report is mostly meaningless, since I have used it in my main game without any issues

**Comment by linuxgurugamer** [comment]
Issue is confirmed, working on it

**Comment by linuxgurugamer** [comment]
Ihave a fix, am testing it now

**Comment by linuxgurugamer** [comment]
Fix is released, thank you for your input.
