### ISSUE TITLE
0.0.8.3 breaks Kerbal Construction Time

### ISSUE THREAD

**Issue by grokineer** [linuxgurugamer/SpaceTuxLibrary#7]
After upgrading to 0.0.8.3, when trying to add a rocket to the [KCT](github.com/linuxgurugamer/KCT) build list an exception is thrown preventing the launch.

<img width="273" alt="Screenshot 2021-12-12 231755" src="https://user-images.githubusercontent.com/96012955/145718193-2769dcae-aea3-4769-a5f1-e44dbefc81d9.png">

This is in KSP 1.12. I confirmed that at least one other user has experienced the same issue; rolling back to the previous SpaceTux release fixes it.

**Comment by willfulZephyr** [comment]
I have the same issue. Rolled back to 0.0.8.2 and was able to continue.

**Comment by VirtualGaming1** [comment]
same im going to role back as well. and was thinking it was a diffrent mod that I just added as well at the same time of updating the mod

**Comment by ghost** [comment]
I'll look into it

**Comment by ghost** [comment]
Next time, please provide the FULL log file, I'm going to have to set up an install to look into this, a log file would have saved me time

**Comment by linuxgurugamer** [comment]
Problem fixed, update SpaceTuxLibrary to0.0.8.4
